### ISSUE TITLE
EventSourced API not enforcing that emitEvent should not receive a collection

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1162]
It's possible to pass a list of events to the emit method and the router must then loop over the list and apply each event individually. Instead, it's trying to apply the passed list.

```java
Caused by: java.lang.RuntimeException: no matching handler for 'class java.util.ArrayList'
	at kalix.springsdk.impl.eventsourcedentity.ReflectiveEventSourcedEntityRouter.$anonfun$eventHandlerLookup$1(ReflectiveEventSourcedEntityRouter.scala:36)
	at scala.collection.immutable.HashMap.getOrElse(HashMap.scala:683)
	at kalix.springsdk.impl.eventsourcedentity.ReflectiveEventSourcedEntityRouter.eventHandlerLookup(ReflectiveEventSourcedEntityRouter.scala:36)
	at kalix.springsdk.impl.eventsourcedentity.ReflectiveEventSourcedEntityRouter.handleEvent(ReflectiveEventSourcedEntityRouter.scala:41)
	at kalix.javasdk.impl.eventsourcedentity.EventSourcedEntityRouter.$anonfun$_internalHandleCommand$1(EventSourcedEntityRouter.scala:114)
	at kalix.javasdk.impl.eventsourcedentity.EventSourcedEntityRouter.$anonfun$_internalHandleCommand$1$adapted(EventSourcedEntityRouter.scala:111)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at kalix.javasdk.impl.eventsourcedentity.EventSourcedEntityRouter._internalHandleCommand(EventSourcedEntityRouter.scala:111)
	at kalix.javasdk.impl.eventsourcedentity.EventSourcedEntitiesImpl.liftedTree1$1(EventSourcedEntitiesImpl.scala:192)
	... 24 common frames omitted
```

**Comment by octonato** [comment]
It turns out that this is not an issue in the Spring SDK, but in the Java SDK. Still need to confirm if the Scala SDK has the same. 

(adapted the title accordingly)

**Comment by octonato** [comment]
Ok, I can confirm that same is happening in Scala. 

I'm quite sure I have done this before, so I guess it's a regression that we never noted. It probably there for some time already. 🤷

**Comment by octonato** [comment]
Yeah, the problem was me. :-)

I was passing a list to `emitEvent` instead of `emitEvents` (with an `s` at the end).

This can happen because we don't type the events, the `emitEvent` receives `Any` and therefore users can easily pass a collection. 

For the Spring SDK, it will probably work if we define an event handler receiving a list of events. Then, it will be converted to a json array and will hit the DB as such. 

For gRPC, the codegen generates unique event handlers per event type. So even if someone passes a list to `emitEvent`, later we won't find a proper event handler to consume the list. 

Arguably, that could even be a valid use case. Users may want to consume a list of events all together on the view side and therefore wants to have a list of events instead of one by one. But that would only work for the Spring SDK. 

I think we have two options here...

Either we check if we are getting a list in `emitEvent` and we then delegate it to `emitEvents` and we log warning. 

Or we just let it crash with a more explicitly message that instructs the user on how to fix it.

**Comment by octonato** [comment]
Changed the title once more now that we understand better the issue.

**Comment by aludwiko** [comment]
> Users may want to consume a list of events all together on the view side and therefore wants to have a list of events instead of one by one

in that case, I think there is something wrong with the events model. Users should create more enriched events or sth like that. I would opt to throw an exception (are change it to the `emitEvents` on the fly) because such a mistake is potentially more problematic for users. If they really need to process more events in one batch they can always wrap it `FatEvent(events: List)` (although it is a smelly solution).

I could start working on that, but I'm not sure if this exception/warning should be done on a user function or proxy side.
