### ISSUE TITLE
Spring SDK: support for Spring Boot 3

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1374]
Spring Boot 3 is out and we should preferably depend on this new vesion.

**Comment by octonato** [comment]
For the record, @mckeeh3 tried it out and run into a ClassNotFoundException. We are possibly dependending on something that is now requiring an extra jar.

**Comment by aludwiko** [comment]
Ok, after bumping to Spring 3 one test is flaky:
```
[info] Test com.example.wiring.EventSourcedEntityIntegrationTest#verifyCounterEventSourcedAfterRestartFromSnapshot() started
[info] 2022-12-27 12:01:10,042 INFO  com.example.wiring.eventsourcedentities.counter.CounterEntity - Restarting counter with commandId=12 commandName=Restart seqNr=10 current=com.example.wiring.eventsourcedentities.counter.Counter@4d1986a6
[info] 2022-12-27 12:01:10,043 ERROR com.example.wiring.eventsourcedentities.counter.CounterEntity - Terminating entity [restartFromSnapshot] due to unexpected failure for command [Restart]
[info] kalix.javasdk.impl.EntityExceptions$EntityException: Unexpected failure: java.lang.reflect.InvocationTargetException
[info] 	at kalix.javasdk.impl.EntityExceptions$EntityException$.apply(EntityExceptions.scala:46)
[info] 	at kalix.javasdk.impl.eventsourcedentity.EventSourcedEntitiesImpl.liftedTree1$1(EventSourcedEntitiesImpl.scala:196)
[info] 	at kalix.javasdk.impl.eventsourcedentity.EventSourcedEntitiesImpl.$anonfun$runEntity$6(EventSourcedEntitiesImpl.scala:186)
[info] 	at akka.stream.impl.fusing.Scan$$anon$11.onPush(Ops.scala:444)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:61)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:57)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:104)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
[info] 	at akka.actor.Actor.aroundReceive(Actor.scala:537)
[info] 	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
[info] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[info] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[info] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[info] Caused by: java.lang.reflect.InvocationTargetException: null
[info] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[info] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[info] 	at kalix.springsdk.impl.MethodInvoker.invoke(CommandHandler.scala:76)
[info] 	at kalix.springsdk.impl.eventsourcedentity.ReflectiveEventSourcedEntityRouter.handleCommand(ReflectiveEventSourcedEntityRouter.scala:88)
[info] 	at kalix.javasdk.impl.eventsourcedentity.EventSourcedEntityRouter._internalHandleCommand(EventSourcedEntityRouter.scala:96)
[info] 	at kalix.javasdk.impl.eventsourcedentity.EventSourcedEntitiesImpl.liftedTree1$1(EventSourcedEntitiesImpl.scala:192)
[info] 	... 24 common frames omitted
[info] Caused by: java.lang.RuntimeException: Forceful restarting entity!
[info] 	at com.example.wiring.eventsourcedentities.counter.CounterEntity.restart(CounterEntity.java:82)
[info] 	... 32 common frames omitted
[info] Test com.example.wiring.EventSourcedEntityIntegrationTest#verifyCounterEventSourcedAfterRestart() started
[info] 2022-12-27 12:01:10,166 INFO  com.example.wiring.eventsourcedentities.counter.CounterEntity - Increasing counter with commandId=2 commandName=Times seqNr=1 current=com.example.wiring.eventsourcedentities.counter.Counter@6a5d0b31 value=2
[info] 2022-12-27 12:01:10,215 INFO  com.example.wiring.eventsourcedentities.counter.CounterEntity - Restarting counter with commandId=4 commandName=Restart seqNr=2 current=com.example.wiring.eventsourcedentities.counter.Counter@34f7e4f8
[info] 2022-12-27 12:01:10,215 ERROR com.example.wiring.eventsourcedentities.counter.CounterEntity - Terminating entity [helloRestart] due to unexpected failure for command [Restart]
[info] kalix.javasdk.impl.EntityExceptions$EntityException: Unexpected failure: java.lang.reflect.InvocationTargetException
[info] 	at kalix.javasdk.impl.EntityExceptions$EntityException$.apply(EntityExceptions.scala:46)
[info] 	at kalix.javasdk.impl.eventsourcedentity.EventSourcedEntitiesImpl.liftedTree1$1(EventSourcedEntitiesImpl.scala:196)
[info] 	at kalix.javasdk.impl.eventsourcedentity.EventSourcedEntitiesImpl.$anonfun$runEntity$6(EventSourcedEntitiesImpl.scala:186)
[info] 	at akka.stream.impl.fusing.Scan$$anon$11.onPush(Ops.scala:444)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:61)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:57)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:104)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
[info] 	at akka.actor.Actor.aroundReceive(Actor.scala:537)
[info] 	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
[info] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[info] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[info] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[info] Caused by: java.lang.reflect.InvocationTargetException: null
[info] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[info] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[info] 	at kalix.springsdk.impl.MethodInvoker.invoke(CommandHandler.scala:76)
[info] 	at kalix.springsdk.impl.eventsourcedentity.ReflectiveEventSourcedEntityRouter.handleCommand(ReflectiveEventSourcedEntityRouter.scala:88)
[info] 	at kalix.javasdk.impl.eventsourcedentity.EventSourcedEntityRouter._internalHandleCommand(EventSourcedEntityRouter.scala:96)
[info] 	at kalix.javasdk.impl.eventsourcedentity.EventSourcedEntitiesImpl.liftedTree1$1(EventSourcedEntitiesImpl.scala:192)
[info] 	... 24 common frames omitted
[info] Caused by: java.lang.RuntimeException: Forceful restarting entity!
[info] 	at com.example.wiring.eventsourcedentities.counter.CounterEntity.restart(CounterEntity.java:82)
[info] 	... 32 common frames omitted
[error] Test com.example.wiring.EventSourcedEntityIntegrationTest.verifyCounterEventSourcedAfterRestart failed: java.lang.IllegalStateException: Timeout on blocking read for 10000000000 NANOSECONDS, took 10.126s
[error]     at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123)
[error]     at reactor.core.publisher.Mono.block(Mono.java:1734)
[error]     at com.example.wiring.EventSourcedEntityIntegrationTest.getCounter(EventSourcedEntityIntegrationTest.java:147)
[error]     at com.example.wiring.EventSourcedEntityIntegrationTest.verifyCounterEventSourcedAfterRestart(EventSourcedEntityIntegrationTest.java:93)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:568)
```
locally sometimes it works.

**Comment by aludwiko** [comment]
From the user function it tests perspective I've noticed this error:
```
java.lang.NoClassDefFoundError: ch/qos/logback/core/model/processor/ModelHandlerBase

	at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:263)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:239)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.reinitialize(LogbackLoggingSystem.java:312)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:73)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	```
	
The solution for that is bumping logback in `kalix-jvm-sdk` to `1.4.5`, but the next error is:
```
java.lang.IllegalStateException: Failed to load ApplicationContext for [ReactiveWebMergedContextConfiguration@32c8e539 testClass = customer.api.CustomerIntegrationTest, locations = [], classes = [customer.Main], contextInitializerClasses = [], activeProfiles = [], propertySourceLocations = [], propertySourceProperties = ["spring.main.allow-bean-definition-overriding=true", "org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true"], contextCustomizers = [[ImportsContextCustomizer@2eced48b key = [kalix.springsdk.testkit.KalixConfigurationTest]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@3b6d844d, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@10289886, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@45efd90f, org.springframework.boot.test.web.reactive.server.WebTestClientContextCustomizer@7d7758be, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@9da1, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@536dbea0, org.springframework.boot.test.context.SpringBootTestAnnotation@4e90f0a5], contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]

	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:142)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:127)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:141)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:97)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:241)
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:138)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$5(ClassBasedTestDescriptor.java:337)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.executeAndMaskThrowable(ClassBasedTestDescriptor.java:342)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$6(ClassBasedTestDescriptor.java:337)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstancePostProcessors(ClassBasedTestDescriptor.java:336)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:259)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:252)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:251)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:29)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$before$0(ClassBasedTestDescriptor.java:184)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:183)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:77)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.helpers.NOPLoggerFactory loaded from file:/Users/andrzej/.m2/repository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.slf4j.helpers.NOPLoggerFactory
	at org.springframework.util.Assert.instanceCheckFailed(Assert.java:713)
	at org.springframework.util.Assert.isInstanceOf(Assert.java:632)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:374)
	```
	
This one is more problematic because we have many slf4j available on the classpath:
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/2954053/209668625-44569233-8e7b-4185-8516-b847a4b3fad2.png">

If I exclude `akka-slf4j_2.13` then the next exception is:
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [kalix.javasdk.testkit.KalixTestKit]: Factory method 'kalixTestKit' threw exception with message: akka.event.slf4j.Slf4jLoggingFilter
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 96 common frames omitted
Caused by: java.lang.ClassNotFoundException: akka.event.slf4j.Slf4jLoggingFilter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	```

**Comment by aludwiko** [comment]
Is it a problem to bump logback and slf4j in akka modules?

**Comment by johanandren** [comment]
Yes (https://github.com/akka/akka/issues/31593)

**Comment by ennru** [comment]
We need to come up with a workaround in the Akka Typed test kit. Slf4j considered it internal API. https://jira.qos.ch/browse/SLF4J-577
