### ISSUE TITLE
Bug: TypeInfo id clash when accessing internal cache

### ISSUE THREAD

**Issue by efgpinto** [lightbend/kalix-jvm-sdk#1556]
This was noticed when running the s2s eventing sample for java ([this](https://github.com/lightbend/kalix-jvm-sdk/tree/main/samples/java-spring-eventsourced-customer-registry)).

If we use the same type identifier for multiple types, we will get some exception like:

```
14:56:53.717 ERROR k.javasdk.impl.action.ActionsImpl - Failure during handling of command customer.api.CustomerEventsService.KalixSyntheticMethodOnESCustomer
java.lang.IllegalStateException: Collision with existing existing mapping class customer.domain.CustomerEvent$CustomerCreated -> customer-created. The same type name can't be used for other class class customer.api.CustomerPublicEvent$Created
        at kalix.javasdk.impl.JsonMessageCodec.$anonfun$lookupTypeHint$3(JsonMessageCodec.scala:71)
        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1940)
        at kalix.javasdk.impl.JsonMessageCodec.lookupTypeHint(JsonMessageCodec.scala:64)
        at kalix.javasdk.impl.JsonMessageCodec.lookupTypeHint(JsonMessageCodec.scala:54)
        at kalix.javasdk.impl.JsonMessageCodec.encodeScala(JsonMessageCodec.scala:40)
        at kalix.javasdk.impl.action.ActionsImpl.effectToResponse(ActionsImpl.scala:122)
        at kalix.javasdk.impl.action.ActionsImpl.handleUnary(ActionsImpl.scala:188)
        at kalix.protocol.action.ActionsHandler$.$anonfun$partial$2(ActionsHandler.scala:118)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by aludwiko** [comment]
I was thinking that a namespace could be a service name, but maybe that requires more investigation.

**Comment by octonato** [comment]
I was tracking this to understand when it was introduced. Well, I knew it, but want to confirm that we only have in starting from 1.2.0-M1. 

So, here it is: https://github.com/lightbend/kalix-jvm-sdk/commit/48343da223e64bd32bb8d201b9d3547b6f589f48 


A easy fix is to not initialize the `JsonMessageCodec` in the `SpringKalixApplication`, but inside the component provider. As such, we can easily create a cache by existing component. 

I'm just not so sure about some edge cases for Workflows. A Workflow can manipulate types from different components. If we have two components re-using some type names, it might clash in the Workflow cache.

**Comment by octonato** [comment]
Another solution is to go back to FQCN when `@TypeName` is not explicitly defined. 

We even had a TODO about it:
https://github.com/lightbend/kalix-jvm-sdk/pull/1395/files#diff-c166aa546916b32a3ad11cc6e52ccac856de414a3d145337a3374eaa87a957caR57

In retrospect, I think it was a bad idea to remove the FQCN. Yes, it make it easier for an user to move the class to another package, but we didn't account for types with same name in different packages.

Btw, our docs still mention that in absence of `@TypeName`, the FQCN will be used. So maybe we should just go back to it.

**Comment by efgpinto** [comment]
> A easy fix is to not initialize the `JsonMessageCodec` in the `SpringKalixApplication`, but inside the component provider. As such, we can easily create a cache by existing component.

I tried this yesterday but I don't think that solves it, not for all cases at least. The one I tested is for an action publishing to s2s eventing. In such action, 2 different models can be used one for parsing the internal domain events and another one to represent the external domain events. If both use the same type names, it still gives you a conflict on the cache even if you have a cache per component.

> Btw, our docs still mention that in absence of @TypeName, the FQCN will be used. So maybe we should just go back to it.

I agree. Although that change is not backwards compatible, right? 


I think these are 2 different problems. One has to do with the fact that type names need to unique accross a service (currently at least) and the other is what should be the default in case a `@TypeName` is not provided.

**Comment by octonato** [comment]
It's backwards incompatible only for the Java SDK (code-first variant) so we may consider that it's acceptable for now.

**Comment by efgpinto** [comment]
For the record, recommendation is for users to provide unique TypeName. We added such note to our docs. Additionally, we reverted to FQCN as a default strategy when no TypeName is provided.
