### ISSUE TITLE
fail: Java SDK integration tests on EventSourcedEntityIntegrationTest

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1645]
Integration tests failing with type url catch issue. It's the first time that I such a failure and seems to be a flaky test which points us to a race when accessing the json codec cache (?).

https://github.com/lightbend/kalix-jvm-sdk/actions/runs/5093184208/jobs/9155571775?pr=1578#step:8:848

```java
2023-05-26 17:05:30,701 ERROR akka.grpc.scaladsl.GrpcExceptionHandler(akka://kalix) - Unhandled error: [View unexpected failure: Couldn't find any method with input type [json.kalix.io/set] in View [com.example.wiring.views.CountersByValueSubscriptions@611d34c1].]
kalix.javasdk.impl.view.ViewException: View unexpected failure: Couldn't find any method with input type [json.kalix.io/set] in View [com.example.wiring.views.CountersByValueSubscriptions@611d34c1].
	at kalix.javasdk.impl.view.ViewException$.apply(ViewException.scala:39)
	at kalix.javasdk.impl.view.ViewsImpl.$anonfun$handle$1(ViewsImpl.scala:116)
	at akka.stream.impl.fusing.Map$$anon$1.onPush(Ops.scala:54)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:528)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:61)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:57)
	at akka.stream.impl.fusing.ActorGraphInterpreter$RequestMore.execute(ActorGraphInterpreter.scala:289)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.NoSuchElementException: Couldn't find any method with input type [json.kalix.io/set] in View [com.example.wiring.views.CountersByValueSubscriptions@611d34c1].
	at kalix.javasdk.impl.view.ReflectiveViewRouter.handleUpdate(ReflectiveViewRouter.scala:85)
	at kalix.javasdk.impl.view.ViewRouter._internalHandleUpdate(ViewRouter.scala:40)
	at kalix.javasdk.impl.view.ViewsImpl.$anonfun$handle$1(ViewsImpl.scala:112)
	... 24 common frames omitted
```

**Comment by aludwiko** [comment]
I fixed that here: https://github.com/lightbend/kalix-jvm-sdk/pull/1642#event-9352968584
