### ISSUE TITLE
Workflows: access to workflowId from the step definition.

### ISSUE THREAD

**Issue by aludwiko** [lightbend/kalix-jvm-sdk#1753]
Such code:
```
    Step withdraw =
        step("withdraw")
            .asyncCall(Withdraw.class, cmd -> {
              String workflowId = commandContext().workflowId();
              ...
            })
```
will throw an exception:
```
kalix.javasdk.impl.WorkflowExceptions$WorkflowException: unexpected exception [CommandContext is only available when handling a command.] while executing step [withdraw]
	at kalix.javasdk.impl.WorkflowExceptions$WorkflowException$.apply(WorkflowExceptions.scala:43)
	at kalix.javasdk.impl.workflow.WorkflowImpl.$anonfun$runWorkflow$6(WorkflowImpl.scala:323)
	at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1430)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
```
we should be able to access `WorkflowContext` from the step definition and execution.

**Comment by antagonist112358** [comment]
@aludwiko - I randomly found this bug while looking through the backlog. It appears this is fixed in "later" (at least latest) versions of the SDK. I _think_ we can close this as "done".

**Comment by aludwiko** [comment]
> It appears this is fixed in "later"

sorry, I find it hard to load this context, where do you see the fix?
