### ISSUE TITLE
Failed to wire ComponentClient

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-jvm-sdk#1812]
I got this error today (once locally, once in prod).

It fails to inject a `ComponentClient` into a `UserEventsListener`, but `UserEventsListener` is an Action so it should just work. There is probably a race condition causing this.

```
2023-10-18 23:33:53.812 app[service-6fdcf8db9d-6h7rw] ERROR k.java.impl.action.ActionsImpl Failure during handling of command user.registry.components.actions.UserEventsListener.KalixSyntheticMethodOnESUser
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'user.registry.components.actions.UserEventsListener' defined in URL [jar:file:/maven/user-registry-1.0-SNAPSHOT.jar!/BOOT-INF/classes!/user/registry/components/actions/UserEventsListener.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'componentClient': FactoryBean threw exception on object creation
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:344)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:225)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1310)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1271)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:484)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:339)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:332)
	at kalix.spring.impl.KalixSpringApplication.$anonfun$actionProvider$1(KalixSpringApplication.scala:403)
	at kalix.javasdk.action.ReflectiveActionProvider.newRouter(ReflectiveActionProvider.java:76)
	at kalix.javasdk.impl.action.ActionsImpl.handleUnary(ActionsImpl.scala:199)
	at kalix.protocol.action.ActionsHandler$.$anonfun$partial$2(ActionsHandler.scala:118)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'componentClient': FactoryBean threw exception on object creation
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:154)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:90)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1823)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1273)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:259)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1640)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1597)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:888)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 29 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: ComponentClient can only be injected in Kalix Actions and Workflows.
	at kalix.spring.impl.KalixSpringApplication$ComponentClientFactoryBean$.getObject(KalixSpringApplication.scala:246)
	at kalix.spring.impl.KalixSpringApplication$ComponentClientFactoryBean$.getObject(KalixSpringApplication.scala:240)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:148)
	... 41 common frames omitted
```

**Comment by octonato** [comment]
Hmm, I afraid that we have a major issue here. 

Here is the code that's throwing that exception.
```scala    
override def getObject: ComponentClient =
  if (threadLocal.get() != null) threadLocal.get()
  else
    throw new BeanCreationException("ComponentClient can only be injected in Kalix Actions and Workflows.")
```

For long we believed that Spring wiring happened in a single thread and we have been relying on thread local to do the internal magic. It seems that we were wrong about it. Still, it's surprising that we didn't hit that before.
